language: go
dist: trusty
sudo: false

env:
  - HUGO_VERSION=0.66.0

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_${HUGO_VERSION}_Linux-64bit.deb

script:
  - env HUGO_ENV=production hugo --gc --minify
  - touch public/.nojekyll
  - echo astropengu.in > public/CNAME

deploy:
  provider: pages
  local_dir: public
  target-branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master

branches:
  only:
    - master
