# ------------------------------
# hugo config
# ------------------------------

title = "astropenguin"
baseURL = "https://astropengu.in/"
defaultContentLanguage = "ja"
theme = "stack"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[author]
name = "Akio Taniguchi"
email = "taniguchi@a.phys.nagoya-u.ac.jp"
link = "https://astropengu.in"

[languages.ja]
weight = 1
languageCode = "ja"
languageName = "Ja"
hasCJKLanguage = true
summaryLength = 100

[languages.en]
weight = 2
languageCode = "en"
languageName = "En"
hasCJKLanguage = false
summaryLength = 80

[[menu.main]]
name = "About"
title = "About me and this website"
identifier = "about"
url = "about"
weight = 1

[[menu.main]]
name = "Posts"
title = "Blog posts"
identifier = "posts"
url = "posts"
weight = 2

[markup.highlight]
lineNos = true
noClasses = false

[mediaTypes."text/plain"]
suffixes = ["md"]

[outputFormats.MarkDown]
mediaType = "text/plain"
isPlainText = true
isHTML = false

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]

[permalinks]
posts = "posts/:filename"

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

# ------------------------------
# theme config
# ------------------------------
