# ------------------------------
# hugo
# ------------------------------
title = "Astropenguin"
baseURL = "https://astropengu.in/"
theme = "hugo-theme-hello-friend"
languageCode = "ja"
defaultContentLanguage = "ja"
preserveTaxonomyNames = true
hasCJKLanguage = true
enableEmoji = true

# Google Analytics
googleAnalytics = "UA-130243023-1"

# Disqus
disqusShortname = "astropenguin"

# use git for lastmod date
enableGitInfo = true

[taxonomies]
tag = "tags"
category = "categories"

[permalinks]
page = "/:slug/"
blog = "/:section/:filename/"

[blackfriday]
hrefTargetBlank = true


# ------------------------------
# hello friend theme
# ------------------------------
[params]
contentTypeName = "blog"
defaultTheme = "light"
showMenuItems = 3
showReadingTime = true

[params.logo]
logoText = "astropenguin"

[[menu.main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/astropenguin"
weight = 5

[[menu.main]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/astropengu_in"
weight = 6
