# ------------------------------
# hugo
# ------------------------------
title = "astropengu.in"
baseURL = "https://astropengu.in/"
theme = "hermit"
languageCode = "en"
preserveTaxonomyNames = true
hasCJKLanguage = true
enableEmoji = true

# Google Analytics
googleAnalytics = "UA-130243023-1"

# use git for lastmod date
enableGitInfo = true

[taxonomies]
tag = "tags"
category = "categories"

[permalinks]
blog = "/:section/:filename/"

[blackfriday]
hrefTargetBlank = true


# ------------------------------
# hermit theme
# ------------------------------
[params]
homeSubtitle = "Akio Taniguchi's Website"
footerCopyright = "Akio Taniguchi"
gitUrl = "https://github.com/astropenguin/website/commit/"
bgImg = "img/background.jpg"

# Date format
dateform        = "Jan 2, 2006"
dateformShort   = "Jan 2"
dateformNum     = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"

# custom css/js
customCSS = ["css/custom.css", "css/prism.css"]
customJS = ["js/twemoji.min.js", "js/prism.min.js", "js/scrollbar.js"]

# Social Icons
[[params.social]]
name = "github"
url = "https://github.com/astropenguin"

[[params.social]]
name = "gitlab"
url = "https://gitlab.com/astropenguin"

[[params.social]]
name = "twitter"
url = "https://twitter.com/astropengu_in"

[[params.social]]
name = "email"
url = "mailto:taniguchi@a.phys.nagoya-u.ac.jp"
