# ------------------------------
# hugo config
# ------------------------------
title = "astropenguin"
baseURL = "https://astropengu.in/"
theme = "loveit"
languageCode = "en"
defaultContentLanguage = "en"
enableGitInfo = true
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true

copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
googleAnalytics = "UA-130243023-1"
paginate = 15

[author]
name = "Akio Taniguchi"
link = "https://astropengu.in"

[permalinks]
posts = "posts/:filename"

[[menu.main]]
identifier = "about"
name = "About"
url = "about"
weight = 1

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "posts"
weight = 2

[markup.highlight]
lineNos = true
noClasses = false

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[privacy.googleAnalytics]
anonymizeIP = true

[privacy.youtube]
privacyEnhanced = true

[mediaTypes."text/plain"]
suffixes = ["md"]

[outputFormats.MarkDown]
mediaType = "text/plain"
isPlainText = true
isHTML = false

[outputs]
home = ["HTML", "RSS"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]

# ------------------------------
# theme config
# ------------------------------
[params]
version = "0.1.X"
description = "Akio Taniguchi's personal website"
subtitle = "Akio Taniguchi's personal website"
home_mode = "post"
home_paginate = 5
socialShare = true
linkToMarkdown = true
since = 2018
dateFormatToUse = "2006-01-02"
license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.gravatar]
email = "taniguchi@a.phys.nagoya-u.ac.jp"

[params.social]
GitHub = "astropenguin"
Twitter = "astropengu_in"
Instagram = "astropengu_in"
Email = "taniguchi@a.phys.nagoya-u.ac.jp"
Facebook = "akio.taniguchi.dr"

[params.share]
enable = true
Twitter = true
Facebook = true
Reddit = true

[params.publisher]
name = "Akio Taniguchi"

[params.publisher.logo]
url = "logo.png"
width = 127
height = 40

[params.logo]
url = "logo.png"
width = 127
height = 40

[params.image]
url = "cover.png"
width = 800
height = 600
