# hugo
# - - - - - - - - - - - - - - -
title                 = "Astropenguin"
baseURL               = "https://astropengu.in/"
hasCJKLanguage        = true
theme                 = "minimo"
enableEmoji           = true
Paginate              = 10
preserveTaxonomyNames = true

# Google Analytics
googleAnalytics = "UA-130243023-1"

# syntax highlight
pygmentsCodefences = true
pygmentsStyle      = "manni"

[taxonomies]
tag = "tags"

[permalinks]
page = "/:slug/"
blog = "/:section/:filename/"


# minimo theme
# - - - - - - - - - - - - - - -
[params.info]
description = "Akio Taniguchi's website"
title404    = "404: Nothing is here!"

[params.assets]
favicon   = "favicon.ico"
customCSS = ["css/custom.css"]
customJS  = ["js/custom.js"]

[params.copyright]
prefix    = "<a href=/>Astropenguin</a>"
holder    = "Akio Taniguchi"
startYear = "2018"
suffix    = ""

[params.settings]
accentColor         = "#ffcd00"
showReadingTime     = true
dateFormat          = "2006-01-02"
listDateFormat      = "2006-01-02"
archiveDateFormat   = "2006-01-02"
hideEntryNavigation = ["page"]

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar  = ["about", "sidebar_menu", "taxonomy_cloud", "search", "social_menu"]
footer   = []

[params.seo]
titleSeparator = "-"

[params.social]
email     = "taniguchi@a.phys.nagoya-u.ac.jp"
github    = "astropenguin"
gitlab    = "astropenguin"
facebook  = "akio.taniguchi.dr"
twitter   = "astropengu_in"
instagram = "astropengu_in"

[params.comments]
enable = false

[params.search]
client = "fuse"