name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      WEBSITE_URL: astropengu.in
      HUGO_URL: https://github.com/gohugoio/hugo/releases/download
      HUGO_TYPE: hugo_extended
      HUGO_VERSION: 0.66.0
    steps:
      - name: Checkout website repo
        uses: actions/checkout@v2
      - name: Initialize theme submodule
        run: |
          git submodule update --init --recursive
      - name: Install hugo
        run: |
          SRC=${HUGO_TYPE}_${HUGO_VERSION}_Linux-64bit.deb
          wget ${HUGO_URL}/v${HUGO_VERSION}/${SRC}
          sudo apt install ./${SRC}
      - name: Build website
        run: |
          env HUGO_ENV=production hugo --gc --minify
          echo $WEBSITE_URL > public/CNAME

      - name: Deploy website to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          force_orphan: true
