name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HUGO_URL: https://github.com/gohugoio/hugo
      HUGO_TYPE: hugo_extended
      HUGO_VERSION: 0.66.0
    steps:
      - uses: actions/checkout@v2
      - name: Install hugo
        run: |
          SRC=${HUGO_TYPE}_${HUGO_VERSION}_Linux-64bit.deb
          wget ${HUGO_URL}/releases/download/v${HUGO_VERSION}/${SRC}
          sudo apt install ./${SRC}
      - name: Build website
        run |
          env HUGO_ENV=production hugo --gc --minify
